version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    ports:
      - "80:80"
    container_name: MyMenu.Api
    environment:
        ASPNETCORE_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: Api/Dockerfile
    depends_on:
    - mymenu-db

  mymenu-db:
    container_name: MyMenu.Db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "SQLserver00"
      ACCEPT_EULA: "Y"

  mymenu-idp:
    image: jboss/keycloak:latest
    container_name: MyMenu.Identity
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/mymenu-realm-export.json
    volumes:
      - ./.containers/identity:/opt/jboss/keycloak/standalone/data
      - ./.files/mymenu-realm-export.json:/tmp/mymenu-realm-export.json
    ports:
      - 18080:8080